[package]
name = "advent2019"
version = "0.1.0"
authors = ["Henley_Contractor, Devereux <dhenley_Contractor@ntst.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
